# Generated by Django 5.1.1 on 2024-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resume_title_resume_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Consultant', 'Consultant'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('UI/UX', 'UI/UX'), ('Human Resource', 'Human Resource'), ('Operations', 'Operations')], max_length=100, null=True),
        ),
    ]
